unsigned int sps_id;
int profile_idc;
int level_idc;
int chroma_format_idc;
int transform_bypass;
int log2_max_frame_num;
int poc_type;
int log2_max_poc_lsb;
int delta_pic_order_always_zero_flag;
int offset_for_non_ref_pic;
int offset_for_top_to_bottom_field;
int poc_cycle_length;
int ref_frame_count;
int gaps_in_frame_num_allowed_flag;
int mb_width;
int mb_height;
int frame_mbs_only_flag;
int mb_aff;
int direct_8x8_inference_flag;
int crop;
unsigned int crop_left;
unsigned int crop_right;
unsigned int crop_top;
unsigned int crop_bottom;
int vui_parameters_present_flag;
AVRational sar;
int video_signal_type_present_flag;
int full_range;
int colour_description_present_flag;
enum AVColorPrimaries color_primaries;
enum AVColorTransferCharacteristic color_trc;
enum AVColorSpace colorspace;
enum AVChromaLocation chroma_location;
int timing_info_present_flag;
uint32_t num_units_in_tick;
uint32_t time_scale;
int fixed_frame_rate_flag;
int32_t offset_for_ref_frame[256];
int bitstream_restriction_flag;
int num_reorder_frames;
int scaling_matrix_present;
uint8_t scaling_matrix4[6][16];
uint8_t scaling_matrix8[6][64];
int nal_hrd_parameters_present_flag;
int vcl_hrd_parameters_present_flag;
int pic_struct_present_flag;
int time_offset_length;
int cpb_cnt;
int initial_cpb_removal_delay_length;
int cpb_removal_delay_length;
int dpb_output_delay_length;
int bit_depth_luma;
int bit_depth_chroma;
int residual_color_transform_flag;
int constraint_set_flags;
uint8_t data[4096];
size_t data_size;